# Documentation on the Linter:
# https://github.com/marketplace/actions/super-linter#how-it-works
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Linter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'master'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Linter
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v3.3.0

      ################################
      # Run Linter against code base #
      ################################
      - name: Linter
        uses: docker://github/super-linter:v2.2.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          DEFAULT_BRANCH: main
          VALIDATE_JSON: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_CSS: true
          DISABLE_ERRORS: true
